echo "Issue 2: The operated markers are not displayed."
echo "Wait, if the marker annotations are saved but not displayed, where are they drawn?"
echo "Let's check the code."
echo "In VECTOR INJECTION block, we create a PDPageContentStream and draw the paths."
echo "However, the markers are not displayed because the content stream might be added BEFORE the imported page contents?"
echo "PDPageContentStream(destDoc, importedPage, PDPageContentStream.AppendMode.APPEND, true, true)"
echo "Actually wait, if destDoc.addPage(importedPage) is adding the page AGAIN, the SECOND page doesn't have the new content stream appended? No, we append to `importedPage` which is the FIRST one."
echo "Wait, when we call importPage, it is added to the document. Then we call addPage(importedPage). Does that mean it's added twice?"
echo "Yes. And maybe the viewer is showing the second copy which doesn't have the graphics state properly closed? No, we use `use { cs -> ... }` so it's closed."
echo "Wait, what if the markers ARE displayed on one of the pages but not the other? Or they are not displayed at all because of something else?"
echo "Wait, in the issue: 'and the operated markers are not displayed. When zoomed in cant drag pdf properly in vertical direction'"
